### ISSUE TITLE
How does a value get written from an event to a characteristic in CoreBluetooth?

### ISSUE THREAD

**Issue by qdot** [dfrankland/bluster#25]
I was poking around the bluster code to get an idea of how things work, and one thing I couldn't trace (and I'm too lazy to try building an example then looking at it in a debugger :) ) is how values go from an event to a Characteristic struct in the CoreBluetooth implementation.

AFAIUI, if a write event comes in from the bluetooth central, it'll be a didReceiveWriteRequests event that's handled here:

https://github.com/dfrankland/bluster/blob/master/src/peripheral/corebluetooth/events.rs#L98

However, that looks like it just fires back the response to the event, but doesn't change anything internally? I'm assuming the value to write comes in via the CBATTRequests that are being responded to. Where is the corresponding value set in the Characteristic struct? Just wondering if I'm missing something happening internally in CoreBluetooth.

I think this is the equivalent to what I'm looking for in the bluez code, where the property is set up:

https://github.com/dfrankland/bluster/blob/40163606e487c72996a9833445a9d8a68a095f2c/src/peripheral/bluez/gatt/characteristic.rs#L76

**Comment by dfrankland** [comment]
I don't think I ever got that far to implement it 😅 What's there is some skeleton code to prevent other devices from failing to write. My initial use case was for making a bluetooth keyboard ([bleboard](https://github.com/dfrankland/bleboard)), but that only needs to be read from.

**Comment by qdot** [comment]
Ok, cool, thanks! That's what I was trying to make sure of. :smiley: 

My solution at the moment is to create and store off async channels in ivars (since you can just make anything a c_void and throw it in there, while also making sure that things free/drop when needed), which seems to be working pretty well over on btleplug.

I've got some use cases for peripherals that I might poke at once btleplug is solid and the projects I'm building it for get their next releases, so I may throw some PRs at you when that's done.
