### ISSUE TITLE
Is there any plan to release new version?

### ISSUE THREAD

**Issue by watiko** [dfrankland/bluster#38]
Thanks to create great library. I used the master version which is not published to crate.io.

https://github.com/watiko/beatble-rs/blob/d6833c944b30613e5c01f36396fb116b2e48c37b/Cargo.toml#L10

I would appreciate it if you publish the new version. Thanks.

**Comment by dfrankland** [comment]
Yeah, we should do this soon. I'll try to do it in the next couple of days.

**Comment by dfrankland** [comment]
My apologies for the delay. I've just published. Thanks for the nudge 👌
