### ISSUE TITLE
Running on Android

### ISSUE THREAD

**Issue by stefnotch** [dfrankland/bluster#40]
I saw the following part of the source code and was wondering if this library actually has Android support. As in, running it on an Android device.

https://github.com/dfrankland/bluster/blob/1065a1aaf2697c9d029aad1aba80b60f6156ce3b/Cargo.toml#L17

**Comment by dfrankland** [comment]
Nope, not even close. Maybe one day?

**Comment by stefnotch** [comment]
Ah, I see. Well, thank you for the quick answer

**Comment by ttiurani** [comment]
This would be a super interesting feature.

I don't know much anything about BT, but when you say "Maybe one day?" do you think @dfrankland that this would be possible? Meaning is the hardware of (most) BT Android devices capable of being a BT receiver? And could you get that to work via NDK or would it need to be a rooted device?

**Comment by stefnotch** [comment]
@ttiurani I think this library https://github.com/deviceplug/btleplug supports being a receiver on Android

**Comment by ttiurani** [comment]
Interesting, because the readme says:

> btleplug is meant to be host/central mode only. If you are interested in peripheral BTLE (i.e. acting like a Bluetooth LE device instead of connecting to one),

which is why I'm here :)
